apiVersion: v1
kind: Service
metadata:
  name: feedback-app-service
spec:
  type: NodePort
  selector:
    app: feedback-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
